In [ ]:
import pandas as pd

validation = pd.read_json(r"user_profiles\user_profiles4.jsonl", lines=True, encoding="utf-8")

C:\Users\johnp\AppData\Local\Temp\ipykernel_12300\2900534619.py:3: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  validation = pd.read_json("user_profiles4.jsonl", lines=True, encoding="utf-8")

ValueError: Expected object or value

In [ ]:
import pandas as pd

simOutput = pd.read_json(r"outputs\output4.jsonl", lines=True, encoding="utf-16")

In [ ]:
clonedBadges = validation[validation["has_cloned_badge"] == True]
len(clonedBadges)

50

In [ ]:
isCurious = validation[validation["is_curious"] == True]
isCurious

,user_id,primary_location,primary_building,primary_workspace,authorized_rooms,authorized_buildings,authorized_locations,is_curious,has_cloned_badge,is_night_shift,behavior_profile,activity_preferences,travel_patterns
59,USER_411f5a7e4a1d4075a1572edc5e9684b7,LOC_100a15b3ee89401aa7800cdef1c05289,BLD_48eb0748769645df9c1b0cee60c00aa7,ROOM_fb5aa25276314dea867a71881803c85d,"[ROOM_fb5aa25276314dea867a71881803c85d, ROOM_a...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
107,USER_a992058760a84b45b9a4f9b9340312c5,LOC_100a15b3ee89401aa7800cdef1c05289,BLD_54b5552ca9764ba7bdebc792d60cac0c,ROOM_4e058b530c1f481aa2f8be1410ec80a7,"[ROOM_4e058b530c1f481aa2f8be1410ec80a7, ROOM_e...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
156,USER_a047d901768c49799635a44b9263127b,LOC_32e989885d4a4123b5b2617e68d4eff5,BLD_a71d04764fcf49a3b741a6aa5f4079c5,ROOM_8486220820c9496c8dd128506a6c8741,"[ROOM_8486220820c9496c8dd128506a6c8741, ROOM_5...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
195,USER_ddb2807b730a4b86a92849ace7eb7c88,LOC_36f7539e354140eebaff33977a2f77dc,BLD_b12b7da8e4ec497fa1fd124468ff8896,ROOM_f9671d2b5007490ea405edc07a41eed6,"[ROOM_f9671d2b5007490ea405edc07a41eed6, ROOM_4...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
202,USER_0e0710f984c444109dafdb577f594045,LOC_4e24cd7edd434e9da31f9426e62a84f8,BLD_47eb8e97381b46dbbce65b8fc5911107,ROOM_b9398e63f1e244c88187f32a6831ad71,"[ROOM_b9398e63f1e244c88187f32a6831ad71, ROOM_4...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9861,USER_6d7f4997d48c41a2867d3b0a571fc4d9,LOC_32e989885d4a4123b5b2617e68d4eff5,BLD_537e3763ad7049d0a33fa5f3293dc4e3,ROOM_603cac4a48e84eac92fd7a206f9c5c17,"[ROOM_603cac4a48e84eac92fd7a206f9c5c17, ROOM_8...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9864,USER_8d7dae14e9bc45e5abdf0c074c541a92,LOC_bf12d07d46c545fb9e1d03d1b468eee5,BLD_c1119fe743c14998907d832dc2cfcbf5,ROOM_b42df5a7dcee4354ab753d4143e08a9f,"[ROOM_b42df5a7dcee4354ab753d4143e08a9f, ROOM_5...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9871,USER_74329a0e55a046c19458174b458281a7,LOC_4e24cd7edd434e9da31f9426e62a84f8,BLD_f1e66ed108d5403cabbede51631cd03b,ROOM_7ba40b4faa1b4b06be65d98a4ca081f0,"[ROOM_7ba40b4faa1b4b06be65d98a4ca081f0, ROOM_d...",[],[],True,True,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9929,USER_abe4da7b2fed4c0584bf3658b33e9f7e,LOC_d73145ce85094a34bec07d59ce7405cf,BLD_02efa5083fbd412eb82ed626e5b57a1c,ROOM_7c2c1fce506743c2ae5057a8fb30902c,"[ROOM_7c2c1fce506743c2ae5057a8fb30902c, ROOM_f...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9990,USER_799945065b1143a5bd4c3fec562fcf18,LOC_d73145ce85094a34bec07d59ce7405cf,BLD_02efa5083fbd412eb82ed626e5b57a1c,ROOM_92acbe2bfb8342618e8274406606bb23,"[ROOM_92acbe2bfb8342618e8274406606bb23, ROOM_f...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."

In [ ]:
successfulEntry = simOutput.groupby("user_id")["success"].all()

filtered = successfulEntry[successfulEntry == True]
#removeDup = successfulEntry["user_id"].unique()
#len(removeDup)
#isCurious[isCurious["user_id"].isin(removeDup)]

trueUsers= filtered.reset_index()["user_id"]

trueUserslist = trueUsers.tolist()

isCurious[isCurious["user_id"].isin(trueUserslist)]

,user_id,primary_location,primary_building,primary_workspace,authorized_rooms,authorized_buildings,authorized_locations,is_curious,has_cloned_badge,is_night_shift,behavior_profile,activity_preferences,travel_patterns
59,USER_411f5a7e4a1d4075a1572edc5e9684b7,LOC_100a15b3ee89401aa7800cdef1c05289,BLD_48eb0748769645df9c1b0cee60c00aa7,ROOM_fb5aa25276314dea867a71881803c85d,"[ROOM_fb5aa25276314dea867a71881803c85d, ROOM_a...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
156,USER_a047d901768c49799635a44b9263127b,LOC_32e989885d4a4123b5b2617e68d4eff5,BLD_a71d04764fcf49a3b741a6aa5f4079c5,ROOM_8486220820c9496c8dd128506a6c8741,"[ROOM_8486220820c9496c8dd128506a6c8741, ROOM_5...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
202,USER_0e0710f984c444109dafdb577f594045,LOC_4e24cd7edd434e9da31f9426e62a84f8,BLD_47eb8e97381b46dbbce65b8fc5911107,ROOM_b9398e63f1e244c88187f32a6831ad71,"[ROOM_b9398e63f1e244c88187f32a6831ad71, ROOM_4...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
323,USER_97f913ad935042fda3b2fdf455441bf1,LOC_bf12d07d46c545fb9e1d03d1b468eee5,BLD_af9c140cab554490a3d78c7542e7a206,ROOM_f43cdd20034e437daaab9aa67dc95ed9,"[ROOM_f43cdd20034e437daaab9aa67dc95ed9, ROOM_6...",[],[],True,True,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
412,USER_ba4bd19044fa40c29fc7b78e7ac5d026,LOC_d73145ce85094a34bec07d59ce7405cf,BLD_1b5e34c858f44a48801954a2a0d3ec81,ROOM_65f3ec7a91464ce8887150ce85c7f7c6,"[ROOM_65f3ec7a91464ce8887150ce85c7f7c6, ROOM_7...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9690,USER_09f75adc791345fb83abf28c5f2610bc,LOC_4e24cd7edd434e9da31f9426e62a84f8,BLD_f1e66ed108d5403cabbede51631cd03b,ROOM_173b76c7663946329754d319261efc75,"[ROOM_173b76c7663946329754d319261efc75, ROOM_d...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9697,USER_9daa7b2e666e4c0a920bd632f813237f,LOC_100a15b3ee89401aa7800cdef1c05289,BLD_54b5552ca9764ba7bdebc792d60cac0c,ROOM_b466eeda7be4452bac83ee76098e666a,"[ROOM_b466eeda7be4452bac83ee76098e666a, ROOM_e...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9748,USER_1b2f87537782434bad02cb446c8f31db,LOC_2f3178401a6d4116970750f0e2b15027,BLD_6e4a113eaae946029a4f0f0270a3c263,ROOM_68d1b0d9dd3c468c8e8300ec9bbf75ef,"[ROOM_68d1b0d9dd3c468c8e8300ec9bbf75ef, ROOM_7...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9819,USER_4376f25c464d4c3d8c7a4aa8cc1d2ed1,LOC_36f7539e354140eebaff33977a2f77dc,BLD_754d0bb528e24940a5fd0246daaae80c,ROOM_7c5b0e5124424deda8b8286b582dd7e6,"[ROOM_7c5b0e5124424deda8b8286b582dd7e6, ROOM_5...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."
9990,USER_799945065b1143a5bd4c3fec562fcf18,LOC_d73145ce85094a34bec07d59ce7405cf,BLD_02efa5083fbd412eb82ed626e5b57a1c,ROOM_92acbe2bfb8342618e8274406606bb23,"[ROOM_92acbe2bfb8342618e8274406606bb23, ROOM_f...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."

In [ ]:
failedEntry = simOutput[simOutput["success"] == False]
curiousUserIds= failedEntry["user_id"].unique()
curiousUserIds
#isCurious[isCurious["user_id"].isin(curiousUserIds)]

array(['USER_234076fc7aa14fd3ab3332321a11f483',
       'USER_565d72c3fe5e456abc561fa9bc903cc5',
       'USER_1566ec0440d748bfa7c015624787ac7e',
       'USER_539b92978c164e67b36f740834c5f6d7',
       'USER_bed4d4f468d0419dbdaba32fc847b1c5',
       'USER_ef3aa53ed86545c5be80d8d9772efbf6',
       'USER_dfb57bb0fec7412896eec5b3bc73131d',
       'USER_57c3f935b7744605a9e0f7111ca6b9df',
       'USER_3b4a50426d224219b3ceec22d3013398',
       'USER_d7ef1eec92df4f19907425fda05cebc4',
       'USER_5854378ffa0a497c8f005738331af182',
       'USER_c089a83a1b13401dab3ffd3d5e972815',
       'USER_1fef433733774424892f5818b33a086a',
       'USER_a8a0af20f5a24daeac0c42adbabdb69c',
       'USER_e14f49a99b3f453ba30ae7b36dfc8d94',
       'USER_89783df30fbf4b679c63f758edb7657a',
       'USER_5417bf83f19e4dffa238b53667b9ccc6',
       'USER_8539c69520b243d790cd18605bdda3e1',
       'USER_76ebf0791e2849ae96ee12ef425e9bf5',
       'USER_03a8349680944a859a22417a577a0784',
       'USER_6e2069d5d36247759e91d01f907fd6ef',
       'USER_d280fd9e16994351bcc8f70cd0b9284e',
       'USER_650fbab189fe400da860dc4103d51260',
       'USER_8016c395fb904c8d99f5d42fe87639f7',
       'USER_c42be78f6d384153aba6cf24de478842',
       'USER_71aa8198774748d9ba94fb44341e55cd',
       'USER_743af387c2a64cd2abed71b91a221377',
       'USER_a3c6fadc020146c1b4ded8e19000fa1b',
       'USER_1d5096e0e3eb449e8bd638bd5b3d071b',
       'USER_22f034fde472434b81a6ff038d6646ce',
       'USER_f3d7edfd1de2445282b09bda22db8c06',
       'USER_51802535e2aa47efa81947b54f824e41',
       'USER_336143659a684ef3ba54de7ed11778ef',
       'USER_49a36cc68a6c4d6d815fe4f1bc0d6805',
       'USER_ce5d01e1e0424e309c7e0a712902afea',
       'USER_a992058760a84b45b9a4f9b9340312c5',
       'USER_e89d49d8b401456fb0f5b3755b3e1f30',
       'USER_2a67bbc8778949d7a9756a00b19c7141',
       'USER_efb76aabc14c46ebbe263c55a378a3f5',
       'USER_8bd6fc6d02274ded9204e1301967f38a',
       'USER_4688615197ae4211b7a2f2f58a7fa03c',
       'USER_d2111e15949d48d0b03e2a9b42f55b22',
       'USER_1122ec8bab934e8ca64a0c5573270d38',
       'USER_4bd33c917e9d4f3e8464eea733ada10e',
       'USER_328e3833172347f48cfe42302eab3ddf',
       'USER_2072a4693de54b79b0f4ed53fd1daf8e',
       'USER_629ca189789c47ff83cb6114f197ec2d',
       'USER_f78118a849a64964aeae33b20b477516',
       'USER_aface4cffff9496eb02d69159c444141',
       'USER_d493448bb0f44614b1630bccfc985e79',
       'USER_9d1301a51e1f494b89e27f33fe4641fb',
       'USER_5c80281950784215a981dbf7e907fdb9',
       'USER_8deabfad6bea438c9ca48415e7319232',
       'USER_1c6228ea483848f786df855202a56dff',
       'USER_770cbcc4e2f94d27baea82c56bfd7268',
       'USER_11d692af70864758bbf55b87f297d7c3',
       'USER_66efeebdca064ed4a0731a929021c836',
       'USER_223735bf36a8465190f0ec8d9275a651',
       'USER_206dc89bba5e494a9d3d8c54b801f8c2',
       'USER_4a86b5d62ac04cc6af95d952d8892ebb',
       'USER_574cbd1d690e4dc2b03415986f12953e',
       'USER_1177a22045f8428392ee036b2ca81eae',
       'USER_b0a47466aa5f4612b2f91271765cb8e5',
       'USER_5b494b1542394060a79eee1a76dc1d15',
       'USER_5bcd067f2cf9417e8924740773992da7',
       'USER_835879befe8243c4b38a03bcec55ad99',
       'USER_21a4c397719246fab2fe8cc34325c424',
       'USER_1ad998b521284cbfa0ad77c045fa6d8a',
       'USER_d54c3e2029f848df8ad1e60d59ab88cc',
       'USER_ea10896f36fa4c2796b9be41748ed246',
       'USER_e0136a2635c9495b8e1c078f79d3e5cb',
       'USER_7b1349506e194639bccfae14455d6444',
       'USER_c510f1a7b0d24204a4373a7575da9ebf',
       'USER_ec51a07aa5b64d8496a4de53dbf47251',
       'USER_cc62871043b34084a4f0e27deb762685',
       'USER_7ad6774c42c04d88995fe9396ae73b00',
       'USER_39dc734325fd4f6e8ea39b52c00cce48',
       'USER_8599e8b0e9d34d1dbc473755d26bf2f1',
       'USER_9127dd33bbdb4ba69c7ff8b97d963484',
       'USER_a544abfd26eb47d58c0799f6b492d825',
       'USER_0fdd4694cad747fcb137a4ed1c778a3f',
       'USER_173641d7cad14bbba1a00d87ef07ed65',
       'USER_c2689eb7dcbf4eea81a4aaaad4c79dec',
       'USER_0943244a15674298b0d8d11982b1f622',
       'USER_430e53397ee64f019f46e2ac1267d777',
       'USER_deb1f44ddbcb4fc0bc2249486d413770',
       'USER_6704910d4ed64539bb8c041cc136fa46',
       'USER_394ef1eebc654f6eaf90ae8e10035be5',
       'USER_cdc1af7735ff48d2bf1e5bcff1d5d14c',
       'USER_518afa3a17294596834a15af71375410',
       'USER_8bec7191c70c469b959020517518e70e',
       'USER_8211d66f735c41eb83a719452e946474',
       'USER_9d27d658804b4b45bc82c779c63b6f73',
       'USER_46fe0b3d99a24dcdb199d4a1e2e68265',
       'USER_1bd7243a005744198b5aa9247f0da9a7',
       'USER_9958ac1766ac43cb8a731fd992599ff5',
       'USER_42a74908c5e64808bc86219133bc23ab',
       'USER_39e3f7d52b344c5db490c9a1dca8e55c',
       'USER_9a9f75a9441549229b3cf6aacc4fa72f',
       'USER_dacd4fc4ba504a3082d0fd2969f403f5',
       'USER_2cd27a4623cb4a74889e11cc7644da1a',
       'USER_f3e40f7ac46043799ef4da3b0ab09db2',
       'USER_2c21b3491e3947b18651f0076796a708',
       'USER_c5ca2d3e74dc439d81a59ded06d98264',
       'USER_027f1b64070743d494145271f6a8ac58',
       'USER_b44bd040e25a48468e638ebdd4b2dcd0',
       'USER_7c3f56b0fe69481fab462412fd03d65b',
       'USER_ac2ef11d35ef4d338ec33b360791676b',
       'USER_10f7953d6aca4a94bb08c3f2eb8ec7df',
       'USER_ae2ba8f1d85f4cb2876483fb8fff6501',
       'USER_03024fc802b045f29ae0867283df8824',
       'USER_28b808c161f54e119b0097736d3f6a0d',
       'USER_2b767e4187aa4badb6ee8c650607f83f',
       'USER_a452c0a0e96c4d028c09a65554ebaa96',
       'USER_ae329d51c6b1483a85a0650c6807bbcb',
       'USER_118859c501a645d298c75e4fe7aa681c',
       'USER_2350d97725e74eafbd2f1efea774dbd4',
       'USER_ff1d8a54258a4341904c0bf7efa6f1ac',
       'USER_34899b7656874d38af8011a3f247b281',
       'USER_6c320ac6483745b690a150e0616baa85',
       'USER_d1d1c4f1364b4d87886c9d85f3bf9baa',
       'USER_476cd210f2304281a4eb7a234e3d5451',
       'USER_44fda9729717481cba9a9d26c597c96e',
       'USER_f2ee521dbc324ae982d11380d0f20c14',
       'USER_51c7e171fdd64ce99fbc634a904bea74',
       'USER_109d36c7948d447f975e4b920d3cb045',
       'USER_c963ba54fd634cfda86c58cc444f553f',
       'USER_0bf6156e1bca4885ac6a83369776850c',
       'USER_73cc036b5dca409890fe480d0547d710',
       'USER_07e5dcd10f764c68a42b3b56e645595c',
       'USER_d1343053c3c84816bf6c748a2159e301',
       'USER_f8dd8a447e21480fafecec7d76c457c4',
       'USER_e04662fd86d64648ba79e7f7eb900403',
       'USER_055720acfec648feb2f6760594010e5c',
       'USER_8e4808d2796548dd8c7fe03778e04661',
       'USER_bb82113f5c424e8e91bea632583a37e0',
       'USER_52fe035c9ce8424989ae0a5f1418d9ed',
       'USER_d12e004651b44f778a4cc66ce43a388e',
       'USER_d0a2cf0164de4f4085cbb1b11566da87',
       'USER_2864570a7d684d43889bef099901836a',
       'USER_35ccd099b8f341f0999d0c2d5245d456',
       'USER_7ba9eb6b3e5749d7947db1d3c3e6a1b7',
       'USER_a03ecbf45a7b476a95e81db99fe2c73f',
       'USER_d8a4d616f5274c8f9df63dcf9e8f2ea2',
       'USER_0cd5d40fcdb9403d89163a45e5a2ad22',
       'USER_39418a8b4d104bd195e75653c62543e6',
       'USER_27bf1a3e36be49daae366d5fbc4d4e7d',
       'USER_80207b0c9cdf4fcdab54b7455119f78b',
       'USER_71d5a9f229d44762bdec5c09ef00736a',
       'USER_72f06f7bd18142c9935593c089195c0f',
       'USER_92cc7d63a2424f6d8172602ef1628ee4',
       'USER_231175319c09437c9f018e5ef8befa5b',
       'USER_d779ca03388444fabb5e0b252dc53dc9',
       'USER_f1e0189b7426459b9421934401312437',
       'USER_23296b9cf2b84d98b63bd9f8757eaa61',
       'USER_33089473e5b841a7a8f7cff44eb11ce1',
       'USER_76551a2be3c44ee5934ea3770f65ff05',
       'USER_7f5546906ee744d0bf0b4e054d7c4d46',
       'USER_4f4b3309571e4fab968b6d02b7c718f9',
       'USER_ae564d50ad034c1ca30f612462b26f32',
       'USER_20d3d025c9d74b61a7ac130308b0aca2',
       'USER_2d29c4f64aef45bdb235398e764f6965',
       'USER_18560af55aea44aeaf0798a2f2ddbb30',
       'USER_e11ef38ccbd9496b994e4bdc0484fba7',
       'USER_2ea670a4989047e9ba00a890f3b6c25f',
       'USER_0c6007e01ea446eba2762148c0d0844c',
       'USER_ae35803e452149f59be17ddc446d900f',
       'USER_89f2121aa93c45199e166d34e1f715e0',
       'USER_c0c62a8839334f6aad30428a608a6f8b',
       'USER_abe4da7b2fed4c0584bf3658b33e9f7e',
       'USER_07a73fe46d4246d7a9f835f93b7daeb4',
       'USER_6d273375dd424e71af45a08e441cf581',
       'USER_4f1e296c97444e47918c252c23cb355f',
       'USER_cb87ad04ebfd44e4bd21a6e726b8dbd8',
       'USER_10149a22babc4f0b8b71255a181eb34c',
       'USER_98c067c937c94bee90023e599153092e',
       'USER_58f9624483d140a987f21e19b50e1da6',
       'USER_6642d1ef4d5e434b8adff55f75ff6e12',
       'USER_45c17ff98e4440358f88dc22be3f194a',
       'USER_108255d7ed7a46c09d2dcaf6fd4f5a7d',
       'USER_6d062b26d617455a9a712a8627ba9d39',
       'USER_62cc64aa5ad14f3397f00f6ad442570f',
       'USER_d92e7a789c484b03a1e26a72ac6b3d19',
       'USER_a7ee608ddcfc46dca490deacf770e529',
       'USER_04773b27dafe4712a0552735ebdff378',
       'USER_bd99407073a64fff816c005ea9f53932',
       'USER_55b03147fc5743868a0a7fe026ea33dd',
       'USER_acaee5b01ed94fd79a643160f6f54cdb',
       'USER_389530dd307b4bf191cf3ebeeadd8ec3',
       'USER_c4ab1c284f94436cbdfcbf1d67edc413',
       'USER_376a654c5ef54f5999dc51cb53b4ad15',
       'USER_72c949434425433ab7e051d1ea7575f2',
       'USER_783d9e9bb2b64174a4c5e57894f07bb5',
       'USER_292a4fbc28814e9d9628ae3382928f34',
       'USER_0d33b8af7413408b854ed85f46fc6941',
       'USER_f8088c4c026546d4a7d623d8f2ebdef5',
       'USER_0f1dd524b04a4c7d96dcd4a76c4aa359',
       'USER_75bde291b47a4704adaed6c007f2b6ce',
       'USER_cd041f9d9a5a437f89dd4086dfb6feee',
       'USER_ca69644cef8f4e078481a10d2b88f35a',
       'USER_3109eb3cbbf94d5699126a8687def722',
       'USER_2f89a07e1171438eb547868b8fb8f074',
       'USER_3a0a6431b1d54bb69472291238b37c08',
       'USER_1da2f451a1214282b12d5ebcb1b63472',
       'USER_31907da7949c443f8723e1cc48c83c8e',
       'USER_b42956b3715d4d7f83d1f0bcd65c1865',
       'USER_c571fb61b9904499aab9ac3db13aae5d',
       'USER_4f70705814154c4f9f35e42e5bb8cca3',
       'USER_b353733d4cbc480e89278efec8cd8831',
       'USER_96dc3549ba0c468e91b73129f611c6f5',
       'USER_09d938cdc0e644718a5297993bfd629f',
       'USER_f5c49167bb004fa298480dac6736e592',
       'USER_fbba7a7e20b244c1ba137a53d9ab7a20',
       'USER_df58abd9aaa547cf96dba4398e032e6f',
       'USER_758cff2fba1b4eeca4a4245ae2b73184',
       'USER_29c0335a758242faa8417da12fe4714d',
       'USER_de4ccef789fd483cac67bf1e1f73ed35',
       'USER_817f7dcf83bb40c9b98ad1fc3339a1bd',
       'USER_29dc12437ff843b9b612596c9068ff44',
       'USER_62c7b578750f45ba9ec9943771632294',
       'USER_8b3505d9e4f7443f8ae5237251529f2a',
       'USER_bb03c39d5682444aaaea205834137939',
       'USER_d4973984349f418588812315cd7b696a',
       'USER_638bd12170e3449fb39302517baa3e35',
       'USER_574ea2fc8bf54a5992223077f1ddfe4f',
       'USER_49039ce0ced445be8721e1709568e401',
       'USER_12c8fcacaf9548a48db661a4053952f9',
       'USER_9325d78a7ff64f988578d90aaa02869d',
       'USER_b35b71ebe2334d41ad799ed81b7a7cea',
       'USER_5a59fb2a36ff421483304d49fa607341',
       'USER_f5b68ea5fb654597bb87263b6a87042a',
       'USER_3e32a6b11e294d09ae6e6ed3fd965b09',
       'USER_94ba5d8336c24182a4a03a6196d43866',
       'USER_49f5ebac492540c1bc6265e87fb9de4b',
       'USER_a3f1c6d1493d42e0b06718c3830e039e',
       'USER_dd20673730ce48a88b5d92536345c230',
       'USER_1f082862ea414a138502f009ca01c52c',
       'USER_09bff66b2bd34a5491b224fc39a592b1',
       'USER_c0ccf0f0595543e88c0a2aac4224bc7f',
       'USER_c43382b2fd8c40f9916870b589cc68a2',
       'USER_904b9ec87bcf4b16a652ddba4ed83477',
       'USER_81f15a7350a14939940c952d8f327570',
       'USER_8d7dae14e9bc45e5abdf0c074c541a92',
       'USER_1659d77c9101471ca8c6194ed2c4486c',
       'USER_f0b9033f3da4496dab44690843dad18e',
       'USER_6de1921e7138477bbf39b7cf37f96cbe',
       'USER_5595eaff09744ccbb7b14a970a11da38',
       'USER_87ca9b8251e04c758bdd0978bcf15bf6',
       'USER_62efe3e075c84e84a059086e7c11c050',
       'USER_186aa3beb6a147e8940ce1109c2222d6',
       'USER_031a5b41115949b2b8d85531fe0310a1',
       'USER_35c8f38be3a144fabd67f17911767c20',
       'USER_268710095e8e4d06983607dae681ede8',
       'USER_ea3957b2306d4365b8b7c2089c6a21f1',
       'USER_3d09536fa52b4497a05d7f70c46c9389',
       'USER_f864a4681ff1495da7f5c75b82a4a110',
       'USER_41cb13c72f874c2a80b1d99601ee68ee',
       'USER_a130d54e81a042328633fc2e31f1cd9b',
       'USER_cacb68628c644c0e8069e358d168486c',
       'USER_c55e9d111217472ea6eafa959c35fc99',
       'USER_e4c38964a7924fd090927345c9255f59',
       'USER_dc838b2d09ca4ca19265f591f25105e3',
       'USER_acd4f500a1c54b1b8558bf1caf59a834',
       'USER_68981fcee16e4d479fcad55770d23076',
       'USER_e1a02249405c4637b34e33855904ec17',
       'USER_1fb8fe0ba1814798a90f618477f58997',
       'USER_b1112d1f4bd34d9c88d7307982fd8f88',
       'USER_6eb7c1615e614e1fb5c4df4b7738f78f',
       'USER_24debce2042f46159509e7e376674070',
       'USER_609853721cca431f972ec73dfa8a0d2d',
       'USER_60ff291f46094f26af9e532830132ff0',
       'USER_56779725940e4f73b2cdc59f505e2509',
       'USER_7ec0e17ecbc44be98f53a2c88a48a8bb',
       'USER_5d3e7ee2bb6142e2a5889dd349ae9026',
       'USER_d01d55d6320d4b1cb7abaa4c4854a6ac',
       'USER_c0bed2e8401d4b4bbb5d42045c6808a5',
       'USER_1126ffd1bddb49089a8fd131026ad999',
       'USER_34d1034f90c44302a1b86c6dc544f2f3',
       'USER_90f59e96fa8e480eab929c20f0834915',
       'USER_cc5d1ddbe8814062806d950543524cf8',
       'USER_4bf13097d3a34681ba598bb2692c6d7f',
       'USER_84dd9d7ac51b4835a262217cc39d59e1',
       'USER_70d6755321d44b2981b7ae0604bf1be7',
       'USER_b18d3d73c47f4b689089c11f4355a0fd',
       'USER_3d322ffd2a9944f4b440c6baeb28f855',
       'USER_b46722e331de488094a75bbaac204b5d',
       'USER_d5e429c99636479a8f9781b5e3221d31',
       'USER_6dbda1941290481088b68374aff593e2',
       'USER_b8896e1421c74e3487a578fe67a7abf9',
       'USER_53cd45ae72eb488c9f87e51e64332fa2',
       'USER_b87a87fd986148eab724ea664321cdc5',
       'USER_8d9e2bbf32664ac1bf796878df73a642',
       'USER_3a012c6f125448ba8f08f81e23629d9b',
       'USER_a6e92482e6ca472bbc832b93cb708119',
       'USER_e0e615c21a184ec28b5acf6769d44ab7',
       'USER_d73b8bcbc9284790a5fc9f76cdec1fb6',
       'USER_d6edbbbfa72047b796dd2340e8f5593a',
       'USER_0cbb4a783c914d1cab66a30270c24bbc',
       'USER_c874adcd5afa4cc3a4abd5504204677f',
       'USER_1ea9ee5681a14c8c84f6575a4d2c34e6',
       'USER_e45ca70c989042ed91b01256aa58c4c0',
       'USER_b8f78aee33324dcaabba47ee1122b4aa',
       'USER_5d6519136e524a4387ff82ee6192e7e5',
       'USER_cf60df6affa24552974974a9005c9002',
       'USER_ff19741421054403a333582c9b016369',
       'USER_e76eb9d53be8457589b45450ed5e09db',
       'USER_21772a4434e54626afddeabd734b7493',
       'USER_0572ee3be75545a69570cd918059ff1e',
       'USER_795935ae509f4c0b997a17c8222e9a79',
       'USER_edfb2692d9714e95b48d20ea0837c5df',
       'USER_287654838a4b4baf8b02580e9a7aab08',
       'USER_c5804401e51f4600bb1bd5502cdfd946',
       'USER_75b4c32b63e64470869c393ef7e2e75b',
       'USER_9f5fb2ec8edc4962bcf4f3a018ffc982',
       'USER_043669b00e9d4332b6a4bd40e6475a27',
       'USER_d67972f5cb91411b8708d21954cb5fe1',
       'USER_f37ee4be2fc645b186a800f2b516c011',
       'USER_9e7662aa77044070b1c4d5350d81b48d',
       'USER_981a9db3720645728debf8eaa02063c2',
       'USER_a371aebfe5c148189c55fe612fcdb702',
       'USER_9d6377f8dcaa487d99c55410e664ea84',
       'USER_32c89427409f4519a63b0dceb15112ff',
       'USER_36740e073c224f6fbcf5fd01cf769f5e',
       'USER_055cbe7aa5bd4d399dede378db2cfd96',
       'USER_1742277bb31c4312992f785360311481',
       'USER_361963bf53c149b0a72545a30fb45b18',
       'USER_84ddc57a042741728aca3be60771c085',
       'USER_1df9edd2bbed448e88aba4a8d2520b68',
       'USER_b5cb601c7a474815b1acf4fa9e43b310',
       'USER_3af3efe0c49f41499403ca42c97f9556',
       'USER_7703c58025fb47a0b4a51c8cd16926b1',
       'USER_3ef2bd07ce60415f925c46e9abed3e40',
       'USER_d6f91e5253854602b56d0c747115b456',
       'USER_0617ccb430464d4ba87d5826c6118dc6',
       'USER_8fa6cda83d9a4b709b1eab7c05b93048',
       'USER_aa33870e58ca4ce6ade5f29403dda07d',
       'USER_dc7c025fb9bc4f3fb0980153d7cf01b9',
       'USER_06596ad2d8374c7e8ec3a62ea450d409',
       'USER_1e0694fc7f704aeca58ac266b7ac2e3c',
       'USER_917a25c9d1384986ab53c4f04b44f87f',
       'USER_060872eb0a6b4ba68edfe3b7c61725f3',
       'USER_0d100a65c1fd406c80bb5eb99c4679ee',
       'USER_f27bd90d39c6497a9e201aa8de51b229',
       'USER_a27005e6864d4732867be37919abedd2',
       'USER_6a71bad255de4f58b494fd04b8c2ec51',
       'USER_c30519db21684772bfaee9f6c67288bb',
       'USER_fff5ef7db46248fc8fc3fb284d6d536b',
       'USER_5dc4582edfa24c86b728552e073fdecb',
       'USER_9020bed4627c4325a79ec7ee8365b92e',
       'USER_75ea23445b1d475f8b7e5e5146673709',
       'USER_c020828447304c4889163d223e88805e',
       'USER_75ad96b5f6604fb095f3ff4ed7e2c569',
       'USER_58b3f55ee19c4e058bd90b425c0fa2d0',
       'USER_c99977bbfadb4d69bec70fe11c8c1c29',
       'USER_5c451862b649453cbb8bcc1d10fb1660',
       'USER_31b8aa596fae44e4b17ba12d71d913dc',
       'USER_3b8ca0de92a44833ab83c9ecc853691a',
       'USER_5a7a5377b06d42d1bde956d0b4834928',
       'USER_38bc19daff94427caab4fb85181b0f1b',
       'USER_5cce58f5bd804db3b3604b3102b26b21',
       'USER_97a215eb7b944f7b95375ff03ccd84a6',
       'USER_4acb74a1a9874416bed565c8098044fb',
       'USER_3eeeb5d904764c9bb4675bab4f6f75ec',
       'USER_e64762b0bd994097a01a9373fcd35524',
       'USER_b4a86107150349c084af81141adc2a25',
       'USER_69b8c13d0e1b47589dc89ae870bbb729',
       'USER_cc8e335558a84590b036445453d731f4',
       'USER_a9f8594fe1214d48aeea3ea090a4716a',
       'USER_06677963c83545ca8cd9ebb201631de0',
       'USER_8e3a9304a7fd4d1cb6a6b1e003059024',
       'USER_63dc13202ff54bdebab88743c1aed15c',
       'USER_69325956e69d4af7a3f2d5e2d79e193e',
       'USER_70efd98234d14705bb8f38d2cbb64775',
       'USER_efe4e533459a4d9bb3adc7e5f243fd0f',
       'USER_19b7f5d74fca40aea2c91d569a227335',
       'USER_7bdd0d9d3757467db83da737606808f9',
       'USER_39550bb78d1144379c101c62034b3203',
       'USER_fe956d2c78814acdb911391b846be95a',
       'USER_10d295f4c35a4ee0af1ecfa2375d3979',
       'USER_3c9c246cbe3740408538eae24434d252',
       'USER_11ac674c83bb49b1be5a1027bb2fe72d',
       'USER_eba25ab53a4c4797921e7ea1611ed5a6',
       'USER_147de3c7e3fd41dfa7a2d257b69c82a1',
       'USER_e4ebb1c1558143f8affe8e4e48b9d86f',
       'USER_4ba7e09e930e4d3f9d8d172882908cd3',
       'USER_6a90bf1252cc47dea506d47d0e71cfd4',
       'USER_4a20d2a2c7744d6aa434ca6061b5a9cb',
       'USER_e019d41237b142de8cfe1a67d3d5bc74',
       'USER_78919c84234040a0bbf72b353e071818',
       'USER_d09e5f78fbb74cddacea9ee3e34363c3',
       'USER_e2c911a5b1e347a8b58acd83ebb107cb',
       'USER_74329a0e55a046c19458174b458281a7',
       'USER_20679e7de15440b19ddcd4a7620a78d3',
       'USER_9452453b88204e9ca657a50fa7ada0d1',
       'USER_cfc759c04a9d49bcb658e3eceba9e701',
       'USER_098e4b1247d3487da442f2eb629175d8',
       'USER_7b03e26270054f1798a5ad110b34cbe1',
       'USER_c4c78768e2534ec394699c7671673a8a',
       'USER_a703e174d5a44804b0ae76dec6c178d3',
       'USER_2d4291d126a2454ab5ddc3d26e06defc',
       'USER_e567a08564884176bbb8cfe5d606dda1',
       'USER_831e1a7270034daea453e4f7d70dfb4a',
       'USER_e69d619c4f434119a6d7e9a4009bb7dc',
       'USER_ca11eec10b01453e817a627816372372',
       'USER_299445e89ab84b02adbba516e458abea',
       'USER_d56bf10ef02f4c56adf3de623f1e5ee0',
       'USER_6b0c316b0db2426798277d194b99d355',
       'USER_3ad100ba94134bdda6fd632a35ef5bbf',
       'USER_3726d024a5a9494da52f17ecf661712b',
       'USER_2e68e473da7d40139a5fd931f2cc9aec',
       'USER_bd3827c4736f4f5e849cf386b7f8f413',
       'USER_fd3b19e8138d409fbfce3d00ddd8824d',
       'USER_0f35d52a8152443695d0e51c19b8626c',
       'USER_1e769a1d32674e1487bb0e70138b3dab',
       'USER_ef146a45267c427a80f9f96c64cc89c2',
       'USER_e50e22a3c93f469791c2458b02f1c081',

In [ ]:
user_ids = [
    "USER_411f5a7e4a1d4075a1572edc5e9684b7"
]
validation[validation["user_id"].isin(user_ids)]

,user_id,primary_location,primary_building,primary_workspace,authorized_rooms,authorized_buildings,authorized_locations,is_curious,has_cloned_badge,is_night_shift,behavior_profile,activity_preferences,travel_patterns
59,USER_411f5a7e4a1d4075a1572edc5e9684b7,LOC_100a15b3ee89401aa7800cdef1c05289,BLD_48eb0748769645df9c1b0cee60c00aa7,ROOM_fb5aa25276314dea867a71881803c85d,"[ROOM_fb5aa25276314dea867a71881803c85d, ROOM_a...",[],[],True,False,False,"{'travel_frequency': 0.15, 'curiosity_level': ...","{'typical_arrival_hour_range': [9, 11], 'typic...","{'primary_building_affinity': 0.85, 'same_loca..."

In [ ]:
validation.loc[170, "travel_patterns"]

{'primary_building_affinity': 0.85,
 'same_location_travel_frequency': 0.1,
 'cross_location_travel_frequency': 0.05,
 'typical_cross_location_travel_time': 6.0,
 'frequent_locations': ['LOC_36f7539e354140eebaff33977a2f77dc'],
 'frequent_buildings': ['BLD_269c3164ae5c409681c3c786f53439a4']}